// netlify/functions/send-email.js (CommonJS)exports.handler = async (event) => {  if (event.httpMethod !== "POST") {    return { statusCode: 405, body: "Method Not Allowed" };  }
  const RESEND_API_KEY = process.env.RESEND_API_KEY;  const FROM_EMAIL = process.env.FROM_EMAIL;  const ADMIN_EMAIL = process.env.ADMIN_EMAIL; // adres masażystki/admina
  if (!RESEND_API_KEY || !FROM_EMAIL || !ADMIN_EMAIL) {    return { statusCode: 500, body: "Missing env: RESEND_API_KEY / FROM_EMAIL / ADMIN_EMAIL" };  }
  let mode, reservation;  try { ({ mode, reservation } = JSON.parse(event.body || "{}")); } catch {    return { statusCode: 400, body: "Invalid JSON" };  }  if (!reservation) return { statusCode: 400, body: "Missing reservation" };
  const subjBase = `${reservation.service || "Usługa"} — ${reservation.date || ""} ${reservation.time || ""}`;
  const htmlTherapist = `    <h2>${mode === "reserve" ? "Nowa rezerwacja" : "Rezerwacja POTWIERDZONA"}</h2>    <p><b>Usługa:</b> ${reservation.service || "-"}</p>    <p><b>Termin:</b> ${reservation.date || ""} ${reservation.time || ""}</p>    <p><b>Klient:</b> ${reservation.client?.name || ""}</p>    <p><b>Email klienta:</b> ${reservation.client?.email || ""}</p>    <p><b>Telefon klienta:</b> ${reservation.client?.phone || ""}</p>    <p><b>Adres klienta:</b> ${reservation.client?.address || ""}</p>    ${reservation.notes ? `<p><b>Uwagi:</b> ${reservation.notes}</p>` : ""}    ${reservation.id ? `<hr/><small>ID: ${reservation.id}</small>` : ""}  `;
  const htmlClient = `    <h2>Potwierdzenie wizyty</h2>    <p>Cześć ${reservation.client?.name || ""},</p>    <p>Potwierdzamy Twoją rezerwację:</p>    <ul>      <li><b>Usługa:</b> ${reservation.service || "-"}</li>      <li><b>Termin:</b> ${reservation.date || ""} ${reservation.time || ""}</li>      ${reservation.price ? `<li><b>Cena:</b> ${reservation.price} zł</li>` : ""}      ${reservation.therapistName ? `<li><b>Terapeutka:</b> ${reservation.therapistName}</li>` : ""}    </ul>    ${reservation.id ? `<hr/><small>ID: ${reservation.id}</small>` : ""}  `;
  const messages = [];  if (mode === "reserve" || !mode) {    messages.push({ from: FROM_EMAIL, to: [ADMIN_EMAIL], subject: `NOWA REZERWACJA: ${subjBase}`, html: htmlTherapist });  } else if (mode === "confirm") {    if (!reservation.client?.email) return { statusCode: 400, body: "Missing client email for confirm" };    messages.push({ from: FROM_EMAIL, to: [ADMIN_EMAIL], subject: `POTWIERDZONO: ${subjBase}`, html: htmlTherapist });    messages.push({ from: FROM_EMAIL, to: [reservation.client.email], subject: `Twoja wizyta potwierdzona: ${subjBase}`, html: htmlClient });  } else {    return { statusCode: 400, body: "Unknown mode" };  }
  for (const msg of messages) {    const resp = await fetch("https://api.resend.com/emails", {      method: "POST",      headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },      body: JSON.stringify(msg),    });    if (!resp.ok) {      const t = await resp.text();      return { statusCode: 502, body: t };    }  }
  return { statusCode: 200, headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ok: true }) };};